name: Deploy to GitHub Pages

# Workflow'un ne zaman çalışacağını belirler
on:
  # main branch'e push olduğunda çalışır
  push:
    branches: [ main ]
  
  # Manuel olarak çalıştırma seçeneği
  workflow_dispatch:

# GitHub Pages için gerekli izinler
permissions:
  contents: read
  pages: write
  id-token: write

# Aynı anda sadece bir deployment çalışmasını sağlar
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      # Dependencies kurulumu
      - name: Install dependencies
        run: npm ci
      
      # Projeyi build etme (eğer build scripti varsa)
      - name: Build project
        run: npm run build
        # Eğer build scripti yoksa bu satırı kaldırabilirsiniz
      
      # GitHub Pages için setup
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # Build sonuçlarını upload etme
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Build edilmiş dosyaların bulunduğu klasör
          # Eğer build scripti yoksa '.' kullanın (root directory)
          path: './dist'

  # Deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
